version: "3"

services: 

    web:
        build: .
        command: bash -c "alembic upgrade head && uvicorn main:app --host 0.0.0.0 --port 8000 --reload"
        volumes: 
            - .:/code
        ports: 
            - "8000:8000"
        depends_on: 
            - db

    db:
        image: postgres:13
        ports:
            - "5432:5432"
        environment: 
            - POSTGRES_USER=postgres
            - POSTGRES_PASSWORD=postgres
            - POSTGRES_DB=pizza_db

    # pgadmin:
    #     container_name: pgadmin
    #     image: dpage/pgadmin4
    #     environment: 
    #         - PGADMIN_DEFAULT_EMAIL=pizza@example.com
    #         - PGADMIN_DEFAULT_PASSWORD=admin
    #         - PGADMIN_CONFIG_SERVER_MODE=True
    #     ports: 
    #         - "5050:80"
    #     depends_on: 
    #         - db
    